server:
  port: 8765

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    account-service:
      path: /accounts/**
      serviceId: account-service
    transaction-service:
      path: /transactions/**
      serviceId: transaction-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
